[flyway]
createSchemas = true
locations = ["filesystem:metrics"]

[environments.default]
user = "postgres"

[environments.localhost]
locations = ["filesystem:metrics"]
url = "jdbc:postgresql://localhost:5432/attributes"

[environments.cluster]
locations = ["filesystem:/tmp/git/pgdb/metrics"]
url = "jdbc:postgresql://postgresql:5432/attributes"
